import Header from '@/components/common/Header';
import './globals.css';
import { getSession } from '@/utils/getSessions';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

//TODO: Header 마이페이지 아이콘클릭시 로그인됬는데도 모달띄워짐

async function fetchUser(id: string) {
  const res = await fetch(`${process.env.LOCAL_URL}/api/users/?id=${id}`, {
    cache: 'no-store',
  });
  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  let id = session?.user?.id;
  const user = await fetchUser(id);

  return (
    <html lang="ko">
      <body>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
