export const dummyCardList = [
  {
    studyImage: '/images/card-dummy-img4.png',
    studyMettings: '매주 토요일 오후 8:00',
    studyTypeisBlue: true,
    studyType: '오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: 'UXUI 디자이너 본질 강화 피그마 스터디',
    studyStart: '06.20',
    studyEnd: '08.08',
    studyPlace: '서울 종로구',
    studyJoinMember: 1,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img5.png',
    studyMettings: '매주 일요일 오후 7:00',
    studyTypeisBlue: true,
    studyType: '오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: '하루 10분 피그마 UXUI 디자인 Figma 스터디',
    studyStart: '06.03',
    studyEnd: '06.17',
    studyPlace: '서울 종로구',
    studyJoinMember: 1,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img6.png',
    studyMettings: '매주 금 오후 9:00',
    studyTypeisBlue: true,
    studyType: '오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: 'UX/UI 디자이너 피그마 아이콘 제작 스터디',
    studyStart: '06.24',
    studyEnd: '08.24',
    studyPlace: '서울 종로구',
    studyJoinMember: 1,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img2.png',
    studyMettings: '매주 일요일 오후 7:00',
    studyTypeisBlue: true,
    studyType: '온라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: '사용성 및 UX에 대한 궁극적인 가이드 스터디',
    studyStart: '07.01',
    studyEnd: '09.02',
    studyPlace: '서울 종로구',
    studyJoinMember: 1,
    studyMember: 4,
  },
];
