export const dummyCardList = [
  {
    studyImage: '/images/card-dummy-img1.png',
    studyMettings: '스터디 시간 미정',
    studyTypeisBlue: true,
    studyType: '오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: 'AI 활용 UXUI 포트폴리오 강의 스터디',
    studyStart: '06.20',
    studyEnd: '06.30',
    studyPlace: '서울 종로구',
    studyJoinMember: 2,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img2.png',
    studyMettings: '모임 날짜 미정',
    studyTypeisBlue: true,
    studyType: '온라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: '블렌더 테크닉 향상 및 피드백 스터디',
    studyStart: '06.20',
    studyEnd: '06.30',
    studyPlace: 'ZOOM',
    studyJoinMember: 3,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img3.png',
    studyMettings: '매주 목 오후 8:00',
    studyTypeisBlue: true,
    studyType: '온∙오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '마케팅',
    studyName: '기획안 작성 노하우 가으이 들을 취준생 구해요!',
    studyStart: '07.01',
    studyEnd: '07.30',
    studyPlace: '서울 종로구',
    studyJoinMember: 1,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img1.png',
    studyMettings: '스터디 시간 미정',
    studyTypeisBlue: true,
    studyType: '오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: 'AI 활용 UXUI 포트폴리오 강의 스터디',
    studyStart: '06.20',
    studyEnd: '06.30',
    studyPlace: '서울 종로구',
    studyJoinMember: 2,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img2.png',
    studyMettings: '모임 날짜 미정',
    studyTypeisBlue: true,
    studyType: '온라인',
    studyCategoryisBlue: false,
    studyCatecory: '디자인',
    studyName: '블렌더 테크닉 향상 및 피드백 스터디',
    studyStart: '06.20',
    studyEnd: '06.30',
    studyPlace: 'ZOOM',
    studyJoinMember: 3,
    studyMember: 4,
  },
  {
    studyImage: '/images/card-dummy-img3.png',
    studyMettings: '매주 목 오후 8:00',
    studyTypeisBlue: true,
    studyType: '온∙오프라인',
    studyCategoryisBlue: false,
    studyCatecory: '마케팅',
    studyName: '기획안 작성 노하우 가으이 들을 취준생 구해요!',
    studyStart: '07.01',
    studyEnd: '07.30',
    studyPlace: '서울 종로구',
    studyJoinMember: 1,
    studyMember: 4,
  },
];

export const dummyUserCardList = [
  {
    userName: '스터링윗미',
    userImage: '/images/user-card-dummy.png',
    intersetName: '자격증',
    intersetLevel: '신입',
    studyMoodContent: '자기주도적인',
    userIndex: 95,
    userStudyCount: 9,
  },
  {
    userName: '열일개발자',
    userImage: '/images/user-card-dummy.png',
    intersetName: '개발∙테크',
    intersetLevel: '시니어',
    studyMoodContent: '열정적인',
    userIndex: 97,
    userStudyCount: 7,
  },
  {
    userName: '갓생살자',
    userImage: '/images/user-card-dummy.png',
    intersetName: '자기계발',
    intersetLevel: '비기너',
    studyMoodContent: '열정적인',
    userIndex: 95,
    userStudyCount: 2,
  },
  {
    userName: '스터링윗미',
    userImage: '/images/user-card-dummy.png',
    intersetName: '자격증',
    intersetLevel: '신입',
    studyMoodContent: '자기주도적인',
    userIndex: 95,
    userStudyCount: 9,
  },
  {
    userName: '열일개발자',
    userImage: '/images/user-card-dummy.png',
    intersetName: '개발∙테크',
    intersetLevel: '시니어',
    studyMoodContent: '열정적인',
    userIndex: 97,
    userStudyCount: 7,
  },
];
