export const study = [
  {
    studyId: 1,
    studyName: 'UXUI 디자이너 본질 강화 피그마 스터디',
    studyPlace: '서울시 종로구',
    studyStart: '07.01(토)',
    studyEnd: '08.01(토)',
    studyType: '온라인',
    studyMember: 4,
    studyJoinMember: 3,
    studyScheduleDate: '오후 8:00 - 9:00',
    studyDaysLeft: 3,
    studyFormDate: '2024.06.15 14:30',
  },
  {
    studyId: 2,
    studyName: '하루 10분 피그마 UXUI 디자인 Figma 스터디',
    studyPlace: 'ZOOM',
    studyStart: '08.01(토)',
    studyEnd: '09.01(토)',
    studyType: '온라인',
    studyMember: 6,
    studyJoinMember: 2,
    studyScheduleDate: '오후 7:00 - 9:00',
    studyDaysLeft: 5,
    studyFormDate: '2024.07.15 14:30',
  },
];
